# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
