# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[(b'at me, using it', b'AT ME, USING IT'), (b'at me, not using it', b'AT ME, NOT USING IT'), (b'not at me', b'NOT AT ME')], default=b'not at me', max_length=15)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('person_who_has_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
