# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171129_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='text',
            field=models.CharField(default='text', max_length=300, verbose_name='Insert Text'),
            preserve_default=False,
        ),
    ]
