# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180114_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='debt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='month_to_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_of_persons',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='payed_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='surface_factor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='total_to_pay',
            field=models.FloatField(default=0),
        ),
    ]
