# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180102_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_in_executive_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_president',
            field=models.BooleanField(default=False),
        ),
    ]
