# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 16:16
from __future__ import unicode_literals

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_importantdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantdate',
            name='due_date',
            field=blog.models.IntegerRangeField(default=1),
        ),
    ]
