# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171128_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='key',
            old_name='person_who_has_key',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='key',
            name='modified_date',
        ),
    ]
