# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180103_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantdate',
            old_name='description',
            new_name='text',
        ),
    ]
