# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180114_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_of_persons',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surface_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
