# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180114_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_of_persons',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='surface_factor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
