# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171130_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollchoice',
            name='question',
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='choice',
            field=models.CharField(max_length=200, verbose_name='Choice 1'),
        ),
        migrations.DeleteModel(
            name='PollChoice',
        ),
    ]
