# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180114_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonbill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
