# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_commonbill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonbill',
            name='date',
            field=models.DateField(default=datetime.date(2018, 1, 14)),
        ),
    ]
