# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171130_1837'),
        ('blog', '0006_auto_20171130_1836'),
    ]

    operations = [
    ]
