# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 16:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180104_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='month_to_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_persons',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='payed_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='surface_factor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='total_to_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')]),
        ),
    ]
