# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_20171206_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='status',
        ),
    ]
