# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180114_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonbill',
            name='date',
            field=models.DateField(default=datetime.date(2017, 12, 14)),
        ),
    ]
