# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180115_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_of_persons',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='surface_factor',
            field=models.FloatField(default=0.0),
        ),
    ]
