# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 19:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180115_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrariIntretinere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consum_apa_rece', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cons. apa rece [mc]')),
                ('apa_rece', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cost apa rece [lei]')),
                ('consum_apa_calda', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cons. apa calda [mc]')),
                ('apa_calda', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cost apa calda [lei]')),
                ('gaze', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cost gaze [lei]')),
                ('energie_parti_comune', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cost en. parti comune [lei]')),
                ('interfon', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cost intr. interfon[lei]')),
                ('deseuri_menajere', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cost deseuri menajere [lei]')),
                ('salarii', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'salarii [lei]')),
                ('caldura', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cost caldura [lei]')),
                ('lift', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'cost intr. lift [lei]')),
                ('cheltuieli_neprevazute', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=b'chelt. neprev. [lei]')),
                ('total_luna_curenta', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('restante', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.AddField(
            model_name='commonbill',
            name='cons_apa_calda',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='commonbill',
            name='cons_apa_rece',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='index_curent_apa_calda',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='index_curent_apa_rece',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='index_vechi_apa_calda',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='index_vechi_apa_rece',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='apa_calda',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='apa_rece',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='cheltuieli_neprevazute',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='deseuri_menajere',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='energie_electrica_parti_comune',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='gaze',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='incalzire_curenta',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='intretinere_interfon',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='intretinere_lift',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='commonbill',
            name='salarii_bloc',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='intrariintretinere',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
