# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 19:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180115_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='index_vechi_apa_rece',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
